### ISSUE TITLE
Error in PABatchTool>@(varargin)this.startBatchProcessCallback(varargin{:}) (line 119)             set(this.handles.button_go,'callback',@this.startBatchProcessCallback);   Error while evaluating UIControl Callback

### ISSUE THREAD

**Issue by sarmadm** [informaton/padaco#67]
Hi

I have used source code from matlab to run batch process on (.csv ) sample data , I seleted10 minutes extract and when I start this error is displayed in matlab : 

Error in PABatchTool>@(varargin)this.startBatchProcessCallback(varargin{:}) (line 119)
            set(this.handles.button_go,'callback',@this.startBatchProcessCallback);

Error while evaluating UIControl Callback

why this error is showing ?

**Comment by informaton** [comment]
There appears to be an error in the single study view mode as well with a non-existent field 'psd_band_1'.  Elevating this issue to bug.

**Comment by sarmadm** [comment]
shall I download source code again and recompile it ?

**Comment by informaton** [comment]
No, not yet.  This is still being worked on.

**Comment by informaton** [comment]
This is resolved now in the master branch as of the latest commit.  Here are the notes:  Update was not occurring with power spectral density band reference in
the single view mode. Possible that other working branch was not
pulled in when this was resolved the first time. Update calls to
secondary display axes as well so that all 5 power bands will be
displayed when selected and also improved secondary axes display to
remove vector magnitude axis when switching from psd feature and
others.
